---
title: "Individual Case Study"
author: "Howard Huang"
date: "December 5, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)
library(rvest)
library(magrittr)
library(fs)

```

```{r}

files = fs::dir_ls("data/current")
testfiles = files[1:10]

```

```{r}

rawData = tibble()

## get the name, table called "per_game", and picture url for each player in the list of files
for(i in 1:length(files)){
  page = read_html(files[i])
  name = page %>% html_nodes("h1") %>% html_text()
  image = page %>% html_nodes("#meta img") %>% html_attr("src")
  stats = page %>% html_nodes("#per_game") %>% html_table() %>% .[[1]] %>% cbind("Name" = name) %>% cbind("Image" = image)
  rawData = rbind(rawData, stats)
}

```

```{r}

playerData = rawData

## make season into an integer by assigning first year of season as year
playerData = playerData %>% mutate("Year" = substr(Season, 1, 4) %>% as.numeric())

## remove all rows that aren't representing a single year (and coerce NA's in the previous step)
playerData = playerData %>% filter(!is.na(Year))

## select necessary variables
playerData = playerData %>% select(Name, Age, Season, Year, Tm, Pos, PTS, TRB, AST, STL, BLK, TOV, `FG%`, `3P%`, `eFG%`, Image)

## recode variables
playerData = playerData %>% 
  mutate(PTS = PTS %>% as.numeric()) %>%
  mutate(TRB = TRB %>% as.numeric()) %>%
  mutate(AST = AST %>% as.numeric()) %>% 
  mutate(STL = STL %>% as.numeric()) %>%
  mutate(BLK = BLK %>% as.numeric()) %>%
  mutate(TOV = TOV %>% as.numeric()) %>%
  mutate(`FG%` = `FG%` %>% as.numeric()) %>%
  mutate(`3P%` = `3P%` %>% as.numeric()) %>%
  mutate(`eFG%` = `eFG%` %>% as.numeric())

```

```{r}

## save that data
saveRDS(playerData, file = "data/currentplayers.rds")

```

```{r}

#what = map_df(
#  testfiles,
#  function(file){
#    page = read_html(file)
#    
#    name = page %>% html_nodes("h1") %>% html_text()
#    team = page %>% html_nodes("#meta div") %>% html_text(trim = T) %>% .[2] %>% 
#  str_replace_all("\r", "") %>% 
#  str_replace_all("\n", "") %>% 
#  str_replace_all("\t", "") %>% 
#  str_replace_all(" ", "")
#    
#  }
#)

```

```{r}

#testfiles[1] %>% read_html() %>% html_nodes("#meta div") %>% html_text(trim = T) %>% .[2] %>% 
#  str_replace_all("\r", "") %>% 
#  str_replace_all("\n", "") %>% 
#  str_replace_all("\t", "") %>% 
#  str_replace_all(" ", "")
#  
#testfiles[1] %>% read_html() %>% html_nodes("#per_game .full_table .center , #per_game .full_table .left , #per_game .full_table #.right") %>% html_table()
#
#what1 = testfiles[1] %>% read_html() %>% html_nodes("#per_game") %>% html_table() %>% .[[1]] %>% cbind("Name" = "what")
#what2 = testfiles[2] %>% read_html() %>% html_nodes("#per_game") %>% html_table() %>% .[[1]] %>% cbind("Name" = "what2")
#
#rbind(what1, what2)

#testfiles[1] %>% read_html() %>% html_nodes("#meta img") %>% html_attr("src")


```